version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  server:
    platform: linux/amd64
    build:
      context: ./server
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  client:
    platform: linux/amd64
    build:
      context: ./client
    ports:
      - "80:80"

volumes:
  mongodb-data:
